CREATE DATABASE myDB;
// sql to create table
  CREATE TABLE MyGuests (
  id INT(200) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  fname VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  phone VARCHAR(100),
  country VARCHAR(100),
  industry VARCHAR(100),
  experience VARCHAR(100),
  skills VARCHAR(300),
  picture VARCHAR(8000),
  reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );